[project]
name = "devto-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-adk>=0.1.0",
    "mcp[cli]>=1.9.1",
    "requests>=2.32.3",
    "termcolor>=3.1.0",
]
